import { FC } from 'react';
import { GuildLayout } from '@theguild/components';
import '@theguild/components/style.css';

export const metadata = {
  // title: 'Next.js',
  // description: 'Generated by Next.js',
};

const RootLayout: FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return <GuildLayout logo={<b>hello</b>}>{children}</GuildLayout>;
};

export default RootLayout;
